#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from analyser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "analyser.y"

    #include <stdio.h>
    #include <string.h>
    #include <stdbool.h>
    #include <stdlib.h>
    #include "defHeader.h"
    extern FILE* yyin;
    extern char* yytext;
    extern int yylineno;
    variable heap[500];
    int sizeOfHeap = 0;
    int getParent(int);
    int getRight(int);
    int getLeft(int);
    bool isLeaf(int);
    int isInHeap(char* );
    void swap(int, int);
    void printHeap();
    void restoreHeap(int);
    void insertInHeap(char*, char*, char*);
    void addSequenceToHeap(char*, char*, char*);
    char *createVarsString(char*, char*);
    variable* getVar(char*, int);

#line 26 "analyser.y"
typedef union{
    char *typeString;
    char *varString;
    char *varsString;
    int addrDepth;
    struct variable *var;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NR	258
#define	MAIN	259
#define	VARTYPE	260
#define	ID	261


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NR;
static const int MAIN;
static const int VARTYPE;
static const int ID;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NR=258
	,MAIN=259
	,VARTYPE=260
	,ID=261


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NR=258;
const int YY_parse_CLASS::MAIN=259;
const int YY_parse_CLASS::VARTYPE=260;
const int YY_parse_CLASS::ID=261;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		52
#define	YYFLAG		-32768
#define	YYNTBASE	15

#define YYTRANSLATE(x) ((unsigned)(x) <= 261 ? yytranslate[x] : 27)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,    14,     2,    11,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    10,     2,
     9,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    12,     2,    13,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     7,     2,     8,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     8,    13,    17,    22,    26,    29,    31,
    35,    40,    45,    47,    51,    54,    57,    59,    62,    64,
    68,    72,    74,    78,    81,    84,    86,    91,    95,    98
};

static const short yyrhs[] = {    21,
    16,     0,    16,    17,     0,    17,     0,     4,     7,    18,
     8,     0,     4,     7,     8,     0,     6,     7,    18,     8,
     0,     6,     7,     8,     0,    18,    19,     0,    19,     0,
    20,     9,    19,     0,    20,     9,    20,    10,     0,    20,
     9,     3,    10,     0,    20,     0,    26,     6,    25,     0,
    26,     6,     0,     6,    25,     0,     6,     0,    21,    22,
     0,    22,     0,     5,    23,    10,     0,    23,    11,    24,
     0,    24,     0,    26,     6,    25,     0,    26,     6,     0,
     6,    25,     0,     6,     0,    25,    12,     3,    13,     0,
    12,     3,    13,     0,    26,    14,     0,    14,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    46,    48,    49,    51,    52,    53,    54,    56,    57,    59,
    79,    98,   105,   113,   114,   115,   116,   119,   120,   122,
   124,   125,   127,   128,   129,   130,   132,   133,   135,   136
};

static const char * const yytname[] = {   "$","error","$illegal.","NR","MAIN",
"VARTYPE","ID","'{'","'}'","'='","';'","','","'['","']'","'*'","s","definitions",
"definition","operations","operation","operand","declarations","declaration",
"variables","variable","staticAddresses","addresses",""
};
#endif

static const short yyr1[] = {     0,
    15,    16,    16,    17,    17,    17,    17,    18,    18,    19,
    19,    19,    19,    20,    20,    20,    20,    21,    21,    22,
    23,    23,    24,    24,    24,    24,    25,    25,    26,    26
};

static const short yyr2[] = {     0,
     2,     2,     1,     4,     3,     4,     3,     2,     1,     3,
     4,     4,     1,     3,     2,     2,     1,     2,     1,     3,
     3,     1,     3,     2,     2,     1,     4,     3,     2,     1
};

static const short yydefact[] = {     0,
     0,     0,    19,    26,    30,     0,    22,     0,     0,     0,
     1,     3,    18,     0,    25,    20,     0,    24,    29,     0,
     0,     2,     0,     0,    21,    23,    17,     5,     0,     9,
    13,     0,     7,     0,    28,     0,    16,     4,     8,     0,
    15,     6,    27,     0,    10,    13,    14,    12,    11,     0,
     0,     0
};

static const short yydefgoto[] = {    50,
    11,    12,    29,    30,    31,     2,     3,     6,     7,    15,
    32
};

static const short yypact[] = {     5,
     1,    25,-32768,    24,-32768,    28,-32768,    19,     4,    33,
    31,-32768,-32768,    29,    34,-32768,     1,    24,-32768,    -2,
    10,-32768,    30,    41,-32768,    34,    24,-32768,    13,-32768,
    36,    20,-32768,    14,-32768,    35,    34,-32768,-32768,    -1,
    24,-32768,-32768,    37,-32768,    32,    34,-32768,-32768,    49,
    50,-32768
};

static const short yypgoto[] = {-32768,
-32768,    40,    38,   -26,    12,-32768,    51,-32768,    39,   -18,
     0
};


#define	YYLAST		59


static const short yytable[] = {    26,
     8,    44,    39,    27,    27,    28,     4,    39,    37,     1,
    20,     5,     5,    45,     5,    27,     8,    33,    27,    27,
    38,    42,    47,     5,    18,    41,     5,     5,     9,     1,
    10,    23,    19,    19,     9,    14,    10,    16,    17,    21,
    40,    49,    35,    36,    40,    24,    48,    43,    51,    52,
    22,    46,    13,     0,     0,    25,     0,     0,    34
};

static const short yycheck[] = {    18,
     1,     3,    29,     6,     6,     8,     6,    34,    27,     5,
     7,    14,    14,    40,    14,     6,    17,     8,     6,     6,
     8,     8,    41,    14,     6,     6,    14,    14,     4,     5,
     6,     3,    14,    14,     4,    12,     6,    10,    11,     7,
     9,    10,    13,     3,     9,    12,    10,    13,     0,     0,
    11,    40,     2,    -1,    -1,    17,    -1,    -1,    21
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 46 "analyser.y"
{printHeap();printf("Analysis complete\n");;
    break;}
case 6:
#line 53 "analyser.y"
{printf("%s\n", yyvsp[-3].varString);;
    break;}
case 7:
#line 54 "analyser.y"
{printf("%s\n", yyvsp[-2].varString);;
    break;}
case 8:
#line 56 "analyser.y"
{printf("Operation result : %s, %s, %s, %d\n", yyvsp[0].var->type, yyvsp[0].var->name, yyvsp[0].var->scope, yyvsp[0].var->depth);;
    break;}
case 9:
#line 57 "analyser.y"
{printf("Operation result : %s, %s, %s, %d\n", yyvsp[0].var->type, yyvsp[0].var->name, yyvsp[0].var->scope, yyvsp[0].var->depth);;
    break;}
case 10:
#line 61 "analyser.y"
{
                    if(yyvsp[-2].var && yyvsp[0].var)
                    {
                        if(yyvsp[-2].var->depth != yyvsp[0].var->depth)
                        {
                            char *leftAddr = (char*)calloc(1, 256);
                            char *rightAddr = (char*)calloc(1, 256);
                            memset(leftAddr, '*', yyvsp[-2].var->depth);
                            memset(rightAddr, '*', yyvsp[0].var->depth);
                            printf("Error at line %d, cannot assign %s%s to %s%s\n", yylineno, rightAddr, yyvsp[0].var->name, leftAddr, yyvsp[-2].var->name);
                            free(leftAddr); free(rightAddr);
                        }
                        yyval.var->depth = yyvsp[-2].var->depth;
                        yyval.var->name = yyvsp[-2].var->name;
                        yyval.var->type = yyvsp[-2].var->type;
                        yyval.var->scope = yyvsp[-2].var->scope;
                    }
                ;
    break;}
case 11:
#line 80 "analyser.y"
{
                    if(yyvsp[-3].var && yyvsp[-1].var)
                    {
                        if(yyvsp[-3].var->depth != yyvsp[-1].var->depth)
                        {
                            char *leftAddr = (char*)calloc(1, 256);
                            char *rightAddr = (char*)calloc(1, 256);
                            memset(leftAddr, '*', yyvsp[-3].var->depth);
                            memset(rightAddr, '*', yyvsp[-1].var->depth);
                            printf("Error at line %d, cannot assign %s%s to %s%s\n", yylineno, rightAddr, yyvsp[-1].var->name, leftAddr, yyvsp[-3].var->name);
                            free(leftAddr); free(rightAddr);
                        }
                        yyval.var->depth = yyvsp[-3].var->depth;
                        yyval.var->name = yyvsp[-3].var->name;
                        yyval.var->type = yyvsp[-3].var->type;
                        yyval.var->scope = yyvsp[-3].var->scope;
                    }
                ;
    break;}
case 12:
#line 100 "analyser.y"
{
                    if(yyvsp[-3].var)
                    if(strcmp(yyvsp[-3].var->type, "int") && strcmp(yyvsp[-3].var->type, "float"))
                        printf("Error at line %d, cannot assign integer to %s\n",yylineno, yyvsp[-3].var->type);
                ;
    break;}
case 13:
#line 107 "analyser.y"
{
                    if(yyvsp[0].var)
                        yyval.var = yyvsp[0].var;
                ;
    break;}
case 14:
#line 113 "analyser.y"
{ yyval.var = getVar(yyvsp[-1].varString, yyvsp[-2].addrDepth+yyvsp[0].addrDepth); if(yyval.var)yyval.var->depth -= yyvsp[-2].addrDepth+yyvsp[0].addrDepth;;
    break;}
case 15:
#line 114 "analyser.y"
{ yyval.var = getVar(yyvsp[0].varString, yyvsp[-1].addrDepth);  if(yyval.var)yyval.var->depth -=yyvsp[-1].addrDepth;;
    break;}
case 16:
#line 115 "analyser.y"
{yyval.var = getVar(yyvsp[-1].varString, yyvsp[0].addrDepth);  if(yyval.var)yyval.var->depth -=yyvsp[0].addrDepth;;
    break;}
case 17:
#line 116 "analyser.y"
{yyval.var = getVar(yyvsp[0].varString, 0);;
    break;}
case 20:
#line 122 "analyser.y"
{char* scope = (char*)malloc(256); strcpy(scope, "global");addSequenceToHeap(scope,yyvsp[-2].typeString,yyvsp[-1].varsString); free(yyvsp[-2].typeString); free(yyvsp[-1].varsString);;
    break;}
case 21:
#line 124 "analyser.y"
{yyval.varsString = createVarsString(yyvsp[-2].varsString, yyvsp[0].varsString);;
    break;}
case 22:
#line 125 "analyser.y"
{ yyval.varsString = createVarsString(yyvsp[0].varsString, NULL);;
    break;}
case 23:
#line 127 "analyser.y"
{char*addrStr = malloc(yyvsp[-2].addrDepth + strlen(yyvsp[-1].varString) + yyvsp[0].addrDepth + 1); memset(addrStr, '*', yyvsp[-2].addrDepth + yyvsp[0].addrDepth); addrStr[yyvsp[-2].addrDepth+yyvsp[0].addrDepth]=0; strcat(addrStr, yyvsp[-1].varString); yyval.varsString=addrStr;;
    break;}
case 24:
#line 128 "analyser.y"
{ char*addrStr = malloc(yyvsp[-1].addrDepth + strlen(yyvsp[0].varString) + 1); memset(addrStr, '*',yyvsp[-1].addrDepth); addrStr[yyvsp[-1].addrDepth] = 0; strcat(addrStr, yyvsp[0].varString); yyval.varsString = addrStr;;
    break;}
case 25:
#line 129 "analyser.y"
{char *addrStr = malloc(yyvsp[0].addrDepth + strlen(yyvsp[-1].varString) +1); memset(addrStr, '*', yyvsp[0].addrDepth); addrStr[yyvsp[0].addrDepth] = 0; strcat(addrStr, yyvsp[-1].varString); yyval.varsString = addrStr;;
    break;}
case 26:
#line 130 "analyser.y"
{yyval.varsString = yyvsp[0].varString;;
    break;}
case 27:
#line 132 "analyser.y"
{yyval.addrDepth = yyvsp[-3].addrDepth + 1;;
    break;}
case 28:
#line 133 "analyser.y"
{yyval.addrDepth = 1;;
    break;}
case 29:
#line 135 "analyser.y"
{yyval.addrDepth = yyvsp[-1].addrDepth + 1; ;
    break;}
case 30:
#line 136 "analyser.y"
{yyval.addrDepth = 1;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 138 "analyser.y"


variable* getVar(char* varName, int varAddrDepth)
{
    int i = isInHeap(varName);
    if( i == 0)
    {
        return NULL;
        printf("Error at line %d, variable %s was not declared in this scope!\n",  yylineno, varName);
    }
    if( heap[i].depth < varAddrDepth )
    {
        char* requested = (char*)calloc(1,256);
        char* have = (char*)calloc(1,256);
        memset(requested, '*', varAddrDepth);
        memset(have, '*', heap[i].depth);
        printf("Error at line %d, variable %s%s exists, but %s%s was requested\n",yylineno, have, varName, requested, varName);
        free(have); free(requested);
        return NULL;
    }
    variable* returned = (variable*)malloc(sizeof(variable));
    returned->depth = heap[i].depth;
    returned->name = heap[i].name;
    returned->type = heap[i].type;
    returned->scope = heap[i].scope;
    return returned;
}

void printHeap()
{
    for(int i = 1; i <= sizeOfHeap; i++)
        printf("Type: %s, Name: %s, Address Depth: %d, Scope: %s\n", heap[i].type, heap[i].name, heap[i].depth, heap[i].scope);
}

int getParent(int index)
{
    return index/2;
}

int getRight(int index)
{
    return index*2 + 1;
}

int getLeft(int index)
{
    return index*2;
}

bool isLeaf(int index)
{
    if( index >= sizeOfHeap/2 && index <= sizeOfHeap)
        return true;
    return false;
}

int isInHeap(char* variable)
{
    for(int i = 1; i <= sizeOfHeap; i++)
    {
        if(strcmp(heap[i].name, variable) == 0)
            return i;
    }
    return 0;
}

void swap(int index1, int index2)
{
    variable auxilliary;
    auxilliary.name = (char*) malloc(256);
    auxilliary.type = (char*) malloc(256);
    auxilliary.scope = (char*)malloc(256);
    strcpy(auxilliary.name, heap[index1].name);
    strcpy(heap[index1].name, heap[index2].name);
    strcpy(heap[index2].name, auxilliary.name);
    strcpy(auxilliary.type, heap[index1].type);
    strcpy(heap[index1].type, heap[index2].type);
    strcpy(heap[index2].type, auxilliary.type);
    strcpy(auxilliary.scope, heap[index1].scope);
    strcpy(heap[index1].scope, heap[index2].scope);
    strcpy(heap[index2].scope, auxilliary.scope);
    auxilliary.depth = heap[index1].depth;
    heap[index1].depth = heap[index2].depth;
    heap[index2].depth = auxilliary.depth;
    free(auxilliary.scope);
    free(auxilliary.type);
    free(auxilliary.name);
}

void restoreHeap(int index)
{
    if( isLeaf(index) )
        return;
    if( strcmp(heap[index].name, heap[getLeft(index)].name ) < 0 || strcmp(heap[index].name, heap[getRight(index)].name) <0)
    {
        if(strcmp(heap[getLeft(index)].name, heap[getRight(index)].name) >0)
        {
            swap(index, getLeft(index));
            restoreHeap(getLeft(index));
        }
        else
        {
            swap(index, getRight(index));
            restoreHeap(getRight(index));
        }
    }
}

void insertInHeap(char* variableTypeString ,char * variableNameString, char * variableDeclarationScope)
{
    printf("Adding %s to heap\n", variableNameString);
    heap[++sizeOfHeap].name = (char*)malloc(256);
    heap[sizeOfHeap].type = (char*)malloc(256);
    heap[sizeOfHeap].scope = (char*)malloc(256);
    strcpy(heap[sizeOfHeap].type, variableTypeString);
    strcpy(heap[sizeOfHeap].name, variableNameString);
    strcpy(heap[sizeOfHeap].scope, variableDeclarationScope);
    heap[sizeOfHeap].depth = 0;

    while(strchr(heap[sizeOfHeap].name, '*'))
    {
        if(heap[sizeOfHeap].name[0]=='*')
        heap[sizeOfHeap].depth++; 
        heap[sizeOfHeap].name++;
    }

    int index = sizeOfHeap;
    while(strcmp(heap[index].name, heap[getParent(index)].name) > 0)
    {
        swap(index, getParent(index));
        index = getParent(index);
    }
}

void addSequenceToHeap(char* scope, char* type,char *sequence)
{
    int i = 0;
    //printf("Adding %s to heap\n", sequence);
    if(sizeOfHeap == 0)
    {
        heap[0].name=(char*)malloc(256);
        memset(heap[0].name, 'z', 256);
        heap[0].name[255] = 0;
    }
    char *variableString = strtok(sequence," ");
    while(variableString)
    {
        if( (i = isInHeap(variableString))> 0)
        if(strcmp(heap[i].scope, scope)==0)
        {
            printf("Error at line %d. Variable %s already declared\n", yylineno, variableString);
        }
        insertInHeap(type, variableString, scope);
        variableString = strtok(NULL, " ");
    }
}

char* createVarsString(char* varSet1, char* varSet2)
{
    char* returnedVarSet = (char*)malloc( strlen(varSet1) + (varSet2 ? strlen(varSet2) : 0) +1 );
    if(varSet2)
    sprintf(returnedVarSet, "%s %s", varSet1, varSet2);
    else
    strcpy(returnedVarSet, varSet1);
    free(varSet1); free(varSet2);
    return returnedVarSet;
}

int yyerror(char *s)
{
    printf("error %s at line %d\n", s, yylineno);
}

int main(int argc, char **argv)
{
    yyin = fopen(argv[1], "r");
    yyparse();
    return 0;
}